### ISSUE TITLE
Status App: [BUG] Installer asks for services but does not save them

### ISSUE THREAD

**Issue by misilot** [gvsulib/library-Status#30]
Also why are 10 services required?

**Comment by mreidsma** [comment]
SQL queries are failing but not stopping the installer. I can't confirm this, since it works fine on both our Dreamhost VPS and running a stock version on MAMP on my local machine. I've heard of one other instance where the installer failed to run, so hoping to get more information on the setup.

In the meantime, I'll add some code to try to catch database errors.

**Comment by mreidsma** [comment]
Removed easy installer, and added it to the road map. It has too many problems to keep supporting, so I'll write a new version this year.
